name: ec2 creation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        uses: actions/checkout@v5

      - name: run terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan
